rvm:
  - 2.2.3
before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -c "create role workshops with password 'pass' login createdb;" -U postgres
  - bundle exec rake db:create db:schema:load
addons:
  postgresql: '9.3'
